### PR TITLE
fix test keyword in README example

### PR DESCRIPTION
**Pull request by jorgepz**
Since the version was changed, the `test` keyword has to be changed.

### CODE REVIEW

**Comment by joergbrech** [comment]
Actually the tests keyword is fine: By writing `uses joergbrech/moxunit-action@v1` you specify that you want to use the *latest* v1.x.x version, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses. Currently, that would be 1.1.

For version 1.1 and higher the keyword is `tests` and not `test_directory`

BTW, that's why I wanted tge version specifier to be changed in #14.

**Comment by jorgepz** [comment]
Thanks for the explanation! I thought that was not right, since I got this warning
```
Warning: Unexpected input(s) 'tests', valid inputs are ['entryPoint', 'args', 'test_directory', 'src_directory']
```
running the v1 at a test repo https://github.com/jorgepz/Octave-Matlab-CI-testbed/runs/1896852522?check_suite_focus=true Maybe I am doing something wrong. Thanks in advance!

**Comment by joergbrech** [comment]
Ah, good to know! Thanks for testing. I always assumed github actions did this automatically, but apparently I have to manage the major release tags myself: https://github.com/marketplace/actions/update-major-version, https://github.com/marketplace/actions/update-major-version

I will take care of it in the next couple of days. Still, I would prefer to only reference the major version in the README for now.

**Comment by jorgepz** [comment]
Great! I guess that after fixing that the warning will be silenced, so I will close this PR.

**Pull request closed without merging**
